### ISSUE TITLE
您好，咨询！

### ISSUE THREAD

**Issue by wjm0913** [niexq/react-app-qiankun-main#13]
公共的登录功能加入集成在基座中。打开基座域名，我登录状态可以分发，我要单独进入子应用的域名，怎么加载登录组件呢

**Comment by niexq** [comment]
> 公共的登录功能加入集成在基座中。打开基座域名，我登录状态可以分发，我要单独进入子应用的域名，怎么加载登录组件呢

很抱歉，还没实践过上述业务场景；

## 看看以下不成文建议是否可行：

+ 1、把登录组件打包 ```npm```发布，借助```webpack``` 的 ```externals```，类复用公共依赖思想；

或

+ 2、把Auth服务单独一个子应用出来，用户信息存本地，Auth子应用可以用setGlobalState，主应用和子应用使用onGlobalStateChange；

希望对你有帮助！

**Comment by wjm0913** [comment]
> > 公共的功能登录集成在进入示例中。打开应用程序，我可以登录到分布式应用程序的域名，如何加载我的独立子子组件，如何加载组件？
> 
> 很抱歉，您的行为已经过上述业务场景；
> 
> ## 查看以下不成文的建议是否有效：
> * 1、把登录组件打包`npm`发布，公共使用`webpack`的`externals`，类复用思想；
> 
> 或者
> 
> * 2、把Auth服务信息单独一个子应用出来，用户保存本地，Auth子应用可以用setGlobalState，主应用和子应用使用onGlobalStateChange；
> 
> 希望对你有帮助！

感谢。
